before_script:
   - eval $(ssh-agent -s)
   - ssh-add ~/.ssh/id_rsa
   - git clone ssh://gitlab-runner@gitlab.leloubil.com/${CI_PROJECT_PATH}.git /tmp/globey
   - cd /tmp/globey
   - docker info

after_script: 
   - rm -r /tmp/globey
stages:
- build
- test
- release

variables:
  DOCKER_IMAGE_TAG : "globey"
  DOCKER_REALEASE_TAG : latest
  GET_SOURCES_ATTEMPTS: "10"


build_image:
  stage: build
  script:
     - "docker build -t $DOCKER_IMAGE_TAG:$CI_COMMIT_REF_SLUG ."


test_bot:
  stage: test
  script:
  - "echo testing"
  #todo

release_image:
  stage: release
  script:
  - "docker tag $DOCKER_IMAGE_TAG:$CI_COMMIT_REF_SLUG $DOCKER_IMAGE_TAG:$DOCKER_REALEASE_TAG"
  only:
  - tags